server:
  log_level: info
  http_tls_config:
    cert_file: /etc/grafana-agent/grafana-cert.pem
    key_file: /etc/grafana-agent/grafana-key.pem

metrics:
  global:
    scrape_interval: 15s
    remote_write:
      - url: http://${prometheus_endpoint}:9090/api/v1/write
  wal_directory: /tmp/grafana-wal
  configs:
    - name: default
      scrape_configs:
        - job_name: grafana
          static_configs:
            - targets: ['localhost:9090']
          relabel_configs:
            - target_label: instance
              replacement: "#MACHINE#"
            - target_label: metrics
              replacement: grafana
            - target_label: role
              replacement: ${role}
            - target_label: stamp
              replacement: XYZ
          tls_config:
            insecure_skip_verify: true
          scheme: https

        - job_name: "vault"
          static_configs:
            - targets: ['localhost:8200']
          relabel_configs:
            - target_label: instance
              replacement: "#MACHINE#"
            - target_label: metrics
              replacement: vault
            - target_label: role
              replacement: ${role}
            - target_label: stamp
              replacement: XYZ
          metrics_path: "/v1/sys/metrics"
          params:
            format: ['prometheus']
          tls_config:
            insecure_skip_verify: true
          scheme: https          

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    # if we need to lower the number of samples and/or the cardinality set explicitly the collectors
    # set_collectors:
    #   - filesystem
    #   - diskstats
    #   - cpu
    #   - meminfo
    #   - loadavg
    #   - uname
    #   - processes
    relabel_configs:
      - target_label: job
        replacement: machine
      - target_label: instance
        replacement: "#MACHINE#"
      - target_label: node
        replacement: "#MACHINE#"
      - target_label: metrics
        replacement: os
      - target_label: role
        replacement: ${role}
      - target_label: stamp
        replacement: XYZ

# LOGS SECTION

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/grafana-log-positions.yaml
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              role: ${role}
              machine: "#MACHINE#"
              stamp: XYZ
              __path__: /var/log/*log
    clients:
      - url: http://${loki_endpoint}:3100/loki/api/v1/push
